name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-release:
    name: "🚀 Create Release"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v4

      - name: "📋 Run Release Please"
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: "📦 Build & Publish"
    runs-on: ubuntu-latest
    needs: create-release
    if: ${{ needs.create-release.outputs.release_created == 'true' }}
    steps:
      - name: "📥 Checkout Released Code"
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.create-release.outputs.tag_name }}

      - name: "🔧 Setup Bun Runtime"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: "📦 Install Dependencies"
        run: bun install --frozen-lockfile

      - name: "🏗️ Build Project"
        run: bun run build

      - name: "🧪 Run Tests"
        run: bun test

      - name: "📤 Publish to npm"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "📦 Create Distribution Archive"
        run: npm pack

      - name: "📤 Upload Release Asset"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: "*.tgz"
          make_latest: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}